name: mscar-python-tutorial-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - matplotlib
  - cartopy
  - nc-time-axis
  - xarray-datatree
  - metpy
  - pip
  - pip:
      - arm_pyart
      - act-atmos
      - intake_esm
      - sphinx-pythia-theme
      - pythia-datasets
