name: mscar-python-tutorial-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.9
  - jupyter-book
  - jupyterlab
  - matplotlib
  - cartopy
  - nc-time-axis
  - xarray-datatree
  - metpy
  - arm_pyart
  - hvplot
  - holoviews
  - geoviews
  - datashader
  - pip
  - pip:
      - act-atmos
      - intake_esm
      - sphinx-pythia-theme
      - pythia-datasets
